### ISSUE TITLE
UPD CaVrefConfig missing on TGL

### ISSUE THREAD

**Issue by c0d3z3r0** [intel/FSP#76] opened 2021-11-21 15:07 UTC
UPD CaVrefConfig missing on TGL

**Comment by nate-desimone** [comment] 2021-11-30 18:47
The CaVrefConfig UPD was removed because the DIMM Vref driver was removed from the Tiger Lake memory controller. This is not a bug, closing.

**Closed by nate-desimone** 2021-11-30 18:47 UTC
